travis:
  secure:
    BINSTAR_TOKEN: WG82mYinZYSDJHVR0QDE17uepRJ10UCJGwN+7eS23uxzYNaxgHOlxMWK7iYONKWcP5QOExtmDbcJ/l2f2fzn7aMpgqEyta/TqT5Rm+ExELAl2aq6E6jV25rhU/7yvtLRPLiVPyQgcjvygGLpuoDqtn+hnkMYSoh+Bs3V2hSXwXLMG1p0iJLJsKOo0YlQ+H6ctyTmXlL0T7kG3G0soHRCS3PRw/D82TdWY2TjLCGiw4Do8HtQ63j60Sq4V5GgCd/GDVlVsUhQBpT5jS8kDfGS2faq2tw03gPSBlIwnY+yAd64J5CFEaCoKR6Z/tjJDCIU+X3eVLyD+8VUeFtpI86IW2Rb6opG0WvENhf8Xi79nUsBJ+4pHM7g8/XffR4rQ3gIKITUi9uUwUphjQIQkfjJePf778Fbk1hzEM2cwZsESS3KUErGYHozfCIPyjETHtDEkA2gLtBGDXLTaMegVnvWVH9YX3Row5LUxcqA+5ccBnlEl+Vm4KXHvlVt6zFZVF+E23TJHrGEsLEUCQVYZmhwQVML0bRP5KHxNnqY1+W4zMfkXRLhkQaM6YfYIsnCKcNqb2apfF/rp7S/WuNodxchISSNVMSxVdculmVI+VX1pFmOjNjXM7lqqLM6Qou7zROlNw1yO+S4Ed90JeTYBR3tGtbiuvSpMQ/dhL1sPwxNrKU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
